name: Test action-ros-ci
on:
  pull_request:
  push:

jobs:
  test_latest:
    runs-on: ubuntu-latest
    container: osrf/ros2:devel
    steps:
    - uses: ros-tooling/setup-ros@v0.7
    - name: Install prerequisites for action-ros-ci and FastRTPS
      run: |
        apt-get -qq update
        apt-get -qq upgrade -y
        apt-get -qq install -y curl libasio-dev libssl-dev libtinyxml2-dev python3-colcon-coveragepy-result
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: |
          sros2
          sros2_cmake
          test_security
        extra-cmake-args: '-DSECURITY=ON --no-warn-unused-cli'
        target-ros2-distro: rolling
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/rolling/ros2.repos
